<?php
/**
 * @file
 * Adds the link to the module to the administration area.
 */

/**
 * Implements hook_menu().
 */
function social_login_menu() {
  // Link to the administration page.
  $items = array();
  $items['admin/config/people/social_login'] = array(
    'title' => 'OneAll Social Login',
    'description' => 'Setup OneAll Social Login and enable the Social Networks of your choice',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array(
      'social_login_admin_settings',
    ),
    'access arguments' => array(
      'administer site configuration',
    ),
    'file' => 'social_login.admin.inc',
  );
  return $items;
}
